// Generated by tools/sync-cocos-assets.mjs from art/asset-manifest.json v3.
// Mode: core-only. Do not edit this file by hand.

export type AssetKey =
  | "avatar.bambooCat.normal"
  | "avatar.flowerFox.normal"
  | "avatar.inkPanda.normal"
  | "avatar.maskedTraveler.normal"
  | "avatar.sleepyStarCat.normal"
  | "avatar.wanderingCrane.normal"
  | "card.back"
  | "card.face.knot"
  | "card.face.leaf"
  | "card.face.mountain"
  | "card.face.sun"
  | "card.special.highest"
  | "card.special.lowest"
  | "font.display"
  | "font.interface"
  | "fx.card.legal"
  | "fx.card.selected"
  | "fx.connection.reconnecting"
  | "fx.prediction.miss"
  | "fx.prediction.success"
  | "fx.trick.win"
  | "scene.teahouse.table"
  | "ui.badge.ai"
  | "ui.bidDots"
  | "ui.countdownRing"
  | "ui.panel.primary"
  | "ui.panel.secondary"
  | "ui.plaque.small"
  | "ui.roundTitleScroll"
  | "ui.scoreRibbon"
  | "ui.status.green"
  | "ui.trumpTile"
  | "ui.turnButton";

export type AssetAddress = Readonly<{
  kind: "spriteFrame" | "font";
  resourcePath: string;
}>;

export const ASSET_KEYS: readonly AssetKey[] = [
  "avatar.bambooCat.normal",
  "avatar.flowerFox.normal",
  "avatar.inkPanda.normal",
  "avatar.maskedTraveler.normal",
  "avatar.sleepyStarCat.normal",
  "avatar.wanderingCrane.normal",
  "card.back",
  "card.face.knot",
  "card.face.leaf",
  "card.face.mountain",
  "card.face.sun",
  "card.special.highest",
  "card.special.lowest",
  "font.display",
  "font.interface",
  "fx.card.legal",
  "fx.card.selected",
  "fx.connection.reconnecting",
  "fx.prediction.miss",
  "fx.prediction.success",
  "fx.trick.win",
  "scene.teahouse.table",
  "ui.badge.ai",
  "ui.bidDots",
  "ui.countdownRing",
  "ui.panel.primary",
  "ui.panel.secondary",
  "ui.plaque.small",
  "ui.roundTitleScroll",
  "ui.scoreRibbon",
  "ui.status.green",
  "ui.trumpTile",
  "ui.turnButton",
];

export const ASSET_ADDRESSES: Record<AssetKey, AssetAddress> = {
  "avatar.bambooCat.normal": { kind: "spriteFrame", resourcePath: "game-art/avatars/bamboo-cat/normal/spriteFrame" },
  "avatar.flowerFox.normal": { kind: "spriteFrame", resourcePath: "game-art/avatars/flower-fox/normal/spriteFrame" },
  "avatar.inkPanda.normal": { kind: "spriteFrame", resourcePath: "game-art/avatars/ink-panda/normal/spriteFrame" },
  "avatar.maskedTraveler.normal": { kind: "spriteFrame", resourcePath: "game-art/avatars/masked-traveler/normal/spriteFrame" },
  "avatar.sleepyStarCat.normal": { kind: "spriteFrame", resourcePath: "game-art/avatars/sleepy-star-cat/normal/spriteFrame" },
  "avatar.wanderingCrane.normal": { kind: "spriteFrame", resourcePath: "game-art/avatars/wandering-crane/normal/spriteFrame" },
  "card.back": { kind: "spriteFrame", resourcePath: "game-art/cards/card-back/spriteFrame" },
  "card.face.knot": { kind: "spriteFrame", resourcePath: "game-art/cards/knot-face/spriteFrame" },
  "card.face.leaf": { kind: "spriteFrame", resourcePath: "game-art/cards/leaf-face/spriteFrame" },
  "card.face.mountain": { kind: "spriteFrame", resourcePath: "game-art/cards/mountain-face/spriteFrame" },
  "card.face.sun": { kind: "spriteFrame", resourcePath: "game-art/cards/sun-face/spriteFrame" },
  "card.special.highest": { kind: "spriteFrame", resourcePath: "game-art/cards/highest-special/spriteFrame" },
  "card.special.lowest": { kind: "spriteFrame", resourcePath: "game-art/cards/lowest-special/spriteFrame" },
  "font.display": { kind: "font", resourcePath: "game-art/fonts/NotoSerifSC-SemiBold-Subset" },
  "font.interface": { kind: "font", resourcePath: "game-art/fonts/NotoSansSC-Medium-Subset" },
  "fx.card.legal": { kind: "spriteFrame", resourcePath: "game-art/ui/legal-halo/spriteFrame" },
  "fx.card.selected": { kind: "spriteFrame", resourcePath: "game-art/ui/selected-halo/spriteFrame" },
  "fx.connection.reconnecting": { kind: "spriteFrame", resourcePath: "game-art/ui/reconnect-spinner/spriteFrame" },
  "fx.prediction.miss": { kind: "spriteFrame", resourcePath: "game-art/ui/prediction-miss/spriteFrame" },
  "fx.prediction.success": { kind: "spriteFrame", resourcePath: "game-art/ui/prediction-success/spriteFrame" },
  "fx.trick.win": { kind: "spriteFrame", resourcePath: "game-art/ui/trick-win/spriteFrame" },
  "scene.teahouse.table": { kind: "spriteFrame", resourcePath: "game-art/backgrounds/teahouse-table/spriteFrame" },
  "ui.badge.ai": { kind: "spriteFrame", resourcePath: "game-art/ui/ai-badge/spriteFrame" },
  "ui.bidDots": { kind: "spriteFrame", resourcePath: "game-art/ui/bid-dots/spriteFrame" },
  "ui.countdownRing": { kind: "spriteFrame", resourcePath: "game-art/ui/countdown-ring/spriteFrame" },
  "ui.panel.primary": { kind: "spriteFrame", resourcePath: "game-art/ui/primary-panel/spriteFrame" },
  "ui.panel.secondary": { kind: "spriteFrame", resourcePath: "game-art/ui/secondary-panel/spriteFrame" },
  "ui.plaque.small": { kind: "spriteFrame", resourcePath: "game-art/ui/small-plaque/spriteFrame" },
  "ui.roundTitleScroll": { kind: "spriteFrame", resourcePath: "game-art/ui/round-title-scroll/spriteFrame" },
  "ui.scoreRibbon": { kind: "spriteFrame", resourcePath: "game-art/ui/score-ribbon/spriteFrame" },
  "ui.status.green": { kind: "spriteFrame", resourcePath: "game-art/ui/green-status/spriteFrame" },
  "ui.trumpTile": { kind: "spriteFrame", resourcePath: "game-art/ui/trump-tile/spriteFrame" },
  "ui.turnButton": { kind: "spriteFrame", resourcePath: "game-art/ui/turn-button/spriteFrame" },
};
